repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, mainline]
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)